### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals-tpch#2]
It would be good to add CI to this repo, which follows the steps on the README and checks that the queries actually execute

**Comment by IsaiasGutierrezCruz** [comment]
It's a good idea. I can take this task c:

**Comment by MarcoGorelli** [comment]
awesome, thanks @IsaiasGutierrezCruz !

**Comment by IsaiasGutierrezCruz** [comment]
Hi @MarcoGorelli!

I was finishing the implementation of this validation, but then I realized that you decided to store the logic of the queries in the main repo, haha.

I implemented a test to validate that the queries actually execute and a workflow exclusively for the tpch directory. Could you please give me your feedback on the implementation? I thought that implementing the validation only in the tpch directory is better than including it in the general tests for narwhals, but I don't know if you agree c: 

Link of the branch: https://github.com/IsaiasGutierrezCruz/narwhals/tree/dev/queries_validation

**Comment by MarcoGorelli** [comment]
ah sorry about that 😄 

looks great, thanks! 🙏 

if these tests would be quite long, maybe we could just execute them when we label PRs with "full-test"? https://stackoverflow.com/a/62331521/4451315

**Comment by IsaiasGutierrezCruz** [comment]
Yes, that sounds great. I already implemented it in this pull request 😃: https://github.com/narwhals-dev/narwhals/pull/899
